### PR TITLE
Catalan and more Spanish translations

### PR DESCRIPTION
**Pull request by zapacni**
This pull request adds Catalan translations

### CODE REVIEW

**Comment by merefield** [comment]
Thanks very much @zapacni.  I've just added 3 more unfortunately, see recent commit - do you want to add before I merge?

**Comment by zapacni** [comment]
Yes, and I'll finish the Spanish translations as well. But one question, at js.user.following_level.regular, is regular talking about trust level 3? So that I can use the name that discourse uses by default. I've also seen occurrences of "user.regular" across the discourse source code but I don't know if this is just a quick way of determining if a user is TL3+ or if it actually means something else different from TL3.

**Comment by zapacni** [comment]
Also, at en.site_settings.follow_following_data_migration, is "Following" referring to the plugin or the following data itself?

**Comment by merefield** [comment]
> js.user.following_level.regular

Is the text you see when not following a user on the selector.

**Comment by merefield** [comment]
> en.site_settings.follow_following_data_migration

I've just removed this @zapacni so you don't need to worry about that one.

It was removed in #29 

Sorry to have so much change in such a short time.  Hopefully things will be stable now.  Thanks for your efforts

**Comment by zapacni** [comment]
@merefield Ok so I removed it then. I also translated the regular string now.

**Comment by merefield** [comment]
Great, ready to merge @zapacni ?

**Comment by zapacni** [comment]
@merefield ready! Just saw the update after a forum I use went through maintenance, and got to see some strings and am satisfied. Unfortunately I can't test for system notifications but I have seen the notifications on-forum correctly translated. I also translated the whole yml file so theoretically it should?

80EC85E5-7DFD-48EF-B9A4-82A7FF80DA92

**Comment by merefield** [comment]
The desktop pop-up ones maybe missing.  Happy to take that as an additional commit.  Will merge this for now and keep it open as I know I might have dropped the ball there.

**Comment by merefield** [comment]
Keeping this open to handle any missing pop-up translations (I'll advise if I find them, will have to look at this tomorrow).

**Pull request merged**
