### PR TITLE
Add follow visibility

### PR DESCRIPTION
**Pull request by angusmcleod**

### CODE REVIEW

**Comment by buildthomas** [comment]
Looks great, thank you so much for this effort @angusmcleod !

**Comment by buildthomas** [comment]
Hey @angusmcleod, what's the timeline for this issue looking like?

**Comment by merefield** [comment]
I've merged this, thanks so much for the work.  However, I will give you some feedback.  It would have been great to have had Notifications as a User setting, not a global site setting.  Also, there should be an option for staff to see the Following, Followers I feel.

**Comment by buildthomas** [comment]
Thanks for the feedback @merefield ! On our forum we are dealing with a very large and young community that likes to game statistics, so to prevent abuse and follower counts feeling competitive, in our case it made more sense to have a site-wide toggle to just turn it off altogether. I definitely agree that there should/could be user options and staff exceptions on top of it.

**Comment by merefield** [comment]
@buildthomas do you have a handle on Meta?

**Comment by buildthomas** [comment]
Just made one here: https://meta.discourse.org/u/buildthomas

**Comment by merefield** [comment]
Got, it.  In any case, a fantastic contribution to the plugin, thanks again!

**Pull request merged**
